[build]
  command = "npm install --include=dev && npm run build"
  functions = "netlify/functions"
  publish = "dist"

[build.environment]
  NODE_ENV = "production"
  NPM_FLAGS = "--include=dev"

[functions]
  external_node_modules = ["@nestjs/core", "@nestjs/common", "@nestjs/platform-express", "compression", "helmet", "axios", "ws", "@vendia/serverless-express"]

[dev]
  command = "npm run start:dev"
  port = 3000

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/api"
  status = 200
